"use strict";
const products = [
  {
    id: 1,
    techType: "mobile",
    name: "iPhone 15 Pro",
    releaseYear: 2023,
    price: 2999,
    sale: true,
    salePrice: 2699,
    bestSeller: true,
    soldCount: 1250000,
    features: {
      brand: "Apple",
      storage: "256GB",
      ram: "8GB",
      display: "6.1 inch OLED",
      camera: "48MP",
    },
    image: "./images/iphone15pro.png",
  },

  {
    id: 2,
    techType: "mobile",
    name: "Samsung Galaxy S24 Ultra",
    releaseYear: 2024,
    price: 3499,
    sale: false,
    bestSeller: true,
    soldCount: 980000,
    features: {
      brand: "Samsung",
      storage: "512GB",
      ram: "12GB",
      display: "6.8 inch AMOLED",
      camera: "200MP",
    },
    image: "./images/samsung_galaxy_s24-removebg-preview.png",
  },

  {
    id: 3,
    techType: "mobile",
    name: "Google Pixel 8",
    releaseYear: 2023,
    price: 1899,
    sale: true,
    newArrival: true,

    salePrice: 1599,
    bestSeller: false,
    features: {
      brand: "Google",
      storage: "128GB",
      ram: "8GB",
      display: "6.2 inch OLED",
      camera: "50MP",
    },
    image: "./images/google_pixel_8-removebg-preview.png",
  },

  {
    id: 4,
    techType: "laptop",
    name: "MacBook Air M3",
    releaseYear: 2024,
    price: 3999,
    sale: false,
    bestSeller: true,
    soldCount: 750000,
    features: {
      brand: "Apple",
      processor: "Apple M3",
      ram: "16GB",
      storage: "512GB SSD",
      screen: "13.6 inch Retina",
    },
    image: "./images/macbook_air_m3-removebg-preview.png",
  },

  {
    id: 5,
    techType: "laptop",
    name: "Lenovo Legion 5",
    releaseYear: 2023,
    price: 3299,
    sale: true,
    salePrice: 2899,
    bestSeller: false,
    features: {
      brand: "Lenovo",
      processor: "AMD Ryzen 7",
      ram: "16GB",
      storage: "1TB SSD",
      gpu: "RTX 4060",
    },
    image: "./images/lenovo_legion_5-removebg-preview.png",
  },

  {
    id: 6,
    techType: "laptop",
    name: "ASUS ROG Strix G16",
    releaseYear: 2024,
    price: 4599,

    sale: false,
    bestSeller: true,
    soldCount: 420000,
    features: {
      brand: "ASUS",
      processor: "Intel Core i9",
      ram: "32GB",
      storage: "1TB SSD",
      gpu: "RTX 4070",
    },

    image: "./images/asus_rog-removebg-preview.png",
  },

  {
    id: 7,
    techType: "tablet",
    name: "iPad Pro M4",
    releaseYear: 2024,
    price: 3199,
    sale: true,
    salePrice: 2899,
    bestSeller: true,
    soldCount: 600000,

    features: {
      brand: "Apple",
      chip: "M4",
      storage: "256GB",
      display: "11 inch OLED",
      battery: "10 hours",
    },

    image: "./images/ipadmfour.png",
  },

  {
    id: 8,
    techType: "tablet",

    name: "Samsung Galaxy Tab S9",
    releaseYear: 2023,
    price: 2499,
    sale: false,
    bestSeller: false,
    features: {
      brand: "Samsung",
      storage: "256GB",
      ram: "12GB",
      display: "11 inch AMOLED",
      penSupport: true,
    },

    image: "./images/samsung_tab-removebg-preview.png",
  },

  {
    id: 9,
    techType: "accessory",
    accessory: " headphone",
    name: "AirPods Pro 2",
    releaseYear: 2022,
    price: 899,
    sale: true,
    salePrice: 749,
    bestSeller: true,

    soldCount: 2300000,
    features: {
      brand: "Apple",
      type: "Wireless Earbuds",
      battery: "6 hours",
      noiseCanceling: true,
      connection: "Bluetooth 5.3",
    },
    image: "./images/airpods pro 2.png",
  },

  {
    id: 10,
    techType: "accessory",
    name: "Logitech MX Master 3S",
    releaseYear: 2022,
    price: 399,
    sale: false,
    bestSeller: true,
    soldCount: 850000,
    features: {
      brand: "Logitech",
      type: "Wireless Mouse",
      dpi: "8000 DPI",
      battery: "70 days",
      connection: "Bluetooth",
    },
    image: "./images/logitech-removebg-preview.png",
  },

  {
    id: 11,
    techType: "accessory",
    name: "Samsung 45W Fast Charger",
    releaseYear: 2023,
    price: 149,
    sale: true,
    salePrice: 99,
    bestSeller: false,
    features: {
      brand: "Samsung",
      power: "45W",
      port: "USB-C",
      cableIncluded: true,
    },
    image: "./images/samsung_charger-removebg-preview.png",
  },
  {
    id: 12,
    techType: "mobile",
    name: "Xiaomi 14 Ultra",
    releaseYear: 2024,
    price: 2799,
    sale: true,
    salePrice: 2399,
    bestSeller: true,
    soldCount: 540000,
    features: {
      brand: "Xiaomi",
      storage: "512GB",
      ram: "16GB",
      display: "6.73 inch AMOLED",
      camera: "50MP Quad Camera",
    },
    image: "./images/xiaomi_14_ultra-removebg-preview.png",
  },

  {
    id: 13,
    techType: "mobile",
    name: "OnePlus 12",
    releaseYear: 2024,
    price: 2299,
    sale: false,
    bestSeller: false,
    features: {
      brand: "OnePlus",
      storage: "256GB",
      ram: "12GB",
      display: "6.82 inch AMOLED",
      battery: "5400mAh",
    },
    image: "./images/one_plus_12-removebg-preview.png",
  },

  {
    id: 14,
    techType: "mobile",
    name: "Nothing Phone 2",
    releaseYear: 2023,
    price: 1599,
    sale: true,
    salePrice: 1299,
    bestSeller: false,
    features: {
      brand: "Nothing",
      storage: "256GB",
      ram: "12GB",
      display: "6.7 inch OLED",
      design: "Transparent Back",
    },
    newArrival: true,

    image: "./images/nothingphone-removebg-preview (1).png",
  },

  {
    id: 15,
    techType: "laptop",
    name: "Dell XPS 13 Plus",
    releaseYear: 2023,
    price: 3899,
    sale: false,
    bestSeller: true,
    soldCount: 350000,
    features: {
      brand: "Dell",
      processor: "Intel Core i7",
      ram: "16GB",
      storage: "512GB SSD",
      screen: "13.4 inch 4K",
    },
    image: "./images/dell_xps-removebg-preview.png",
  },

  {
    id: 16,
    techType: "laptop",
    name: "HP Spectre x360",
    releaseYear: 2024,
    price: 3599,
    sale: true,
    salePrice: 3199,
    bestSeller: false,
    features: {
      brand: "HP",
      processor: "Intel Core Ultra 7",
      ram: "16GB",
      storage: "1TB SSD",
      screen: "OLED Touch",
    },
    image: "./images/hp_spectre-removebg-preview.png",
  },

  {
    id: 17,
    techType: "laptop",
    name: "Acer Predator Helios Neo",
    releaseYear: 2024,
    price: 4199,
    sale: false,
    bestSeller: true,
    soldCount: 280000,
    features: {
      brand: "Acer",
      processor: "Intel Core i7",
      ram: "32GB",
      storage: "1TB SSD",
      gpu: "RTX 4070",
    },
    image: "./images/acer_predator-removebg-preview.png",
  },

  {
    id: 18,
    techType: "tablet",
    name: "Microsoft Surface Pro 10",
    releaseYear: 2024,
    price: 2999,
    sale: false,
    bestSeller: false,
    features: {
      brand: "Microsoft",
      processor: "Intel Core Ultra 5",
      ram: "16GB",
      storage: "512GB SSD",
      display: "13 inch PixelSense",
    },
    image: "./images/microsoft_surface-removebg-preview.png",
  },

  {
    id: 19,
    techType: "tablet",
    name: "Lenovo Tab P12",
    releaseYear: 2023,
    newArrival: true,

    price: 1199,
    sale: true,
    salePrice: 999,
    bestSeller: false,
    features: {
      brand: "Lenovo",
      storage: "128GB",
      ram: "8GB",
      display: "12.7 inch LCD",
      speakers: "JBL Quad Speakers",
    },
    image: "./images/lenovo_tab-removebg-preview.png",
  },

  {
    id: 20,
    techType: "tablet",
    name: "Huawei MatePad 11.5",
    releaseYear: 2023,
    price: 999,
    sale: true,
    salePrice: 799,
    bestSeller: false,
    features: {
      brand: "Huawei",
      storage: "128GB",
      ram: "6GB",
      display: "11.5 inch LCD",
      battery: "7700mAh",
    },
    image: "./images/huawei_matepad-removebg-preview.png",
  },

  {
    id: 21,
    techType: "accessory",
    name: "Sony WH-1000XM5",
    accessory: " headphone",
    releaseYear: 2022,
    price: 1199,
    sale: false,
    bestSeller: true,
    soldCount: 1500000,
    features: {
      brand: "Sony",
      type: "Wireless Headphones",
      noiseCanceling: true,
      battery: "30 hours",
      connection: "Bluetooth 5.2",
    },
    image: "./images/sony-Photoroom.png",
  },

  {
    id: 22,
    techType: "accessory",
    name: "Razer BlackWidow V4 Keyboard",
    releaseYear: 2023,
    price: 699,
    sale: true,
    salePrice: 549,
    bestSeller: false,
    features: {
      brand: "Razer",
      type: "Gaming Keyboard",
      switches: "Mechanical",
      rgb: true,
      connection: "USB",
    },

    image: "./images/razer_keybord-removebg-preview.png",
  },

  {
    id: 23,
    techType: "accessory",
    name: "Apple Watch Series 9",
    releaseYear: 2023,
    price: 1299,
    sale: false,
    bestSeller: true,
    soldCount: 900000,
    features: {
      brand: "Apple",
      display: "45mm Retina",
      waterproof: true,
      battery: "18 hours",
      healthSensors: true,
    },
    newArrival: true,
    image: "./images/appleWatch-Photoroom.png",
  },

  {
    id: 24,
    techType: "accessory",
    name: "JBL Charge 5",
    releaseYear: 2021,
    price: 499,
    sale: true,
    salePrice: 399,
    bestSeller: true,
    soldCount: 1100000,
    features: {
      brand: "JBL",
      type: "Bluetooth Speaker",
      battery: "20 hours",
      waterproof: true,
      power: "40W",
    },
    image: "./images/jbl dyn-Photoroom.png",
  },
];
