create table public.categories (id bigint generated by default as identity primary key, name text not null unique, slug text not null unique, created_at timestamptz not null default now());
create table public.brands (id bigint generated by default as identity primary key, name text not null unique, slug text not null unique, created_at timestamptz not null default now());
create table public.products (
 id bigint generated by default as identity primary key,
 category_id bigint references public.categories(id) on delete restrict,
 brand_id bigint references public.brands(id) on delete restrict,
 name text not null,
 slug text not null unique,
 description text not null default '',
 price numeric(12,2) not null check(price>=0),
 sale_price numeric(12,2) check(sale_price>=0 and sale_price<=price),
 currency text not null default 'GEL' check(currency='GEL'),
 specifications jsonb not null default '{}'::jsonb check(jsonb_typeof(specifications)='object'),
 stock_quantity integer not null default 0 check(stock_quantity>=0),
 is_active boolean not null default true,
 is_purchasable boolean not null default false,
 is_bestseller boolean not null default false,
 is_new_arrival boolean not null default false,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create index products_category_idx on public.products(category_id);
create index products_brand_idx on public.products(brand_id);
create table public.product_images (
 id bigint generated by default as identity primary key,
 product_id bigint not null references public.products(id) on delete cascade,
 storage_path text not null check(length(trim(storage_path))>0),
 alt_text text not null default '',
 display_order integer not null default 0 check(display_order>=0),
 is_primary boolean not null default false,
 created_at timestamptz not null default now(),
 unique(product_id,storage_path)
);
create unique index one_primary_image_per_product on public.product_images(product_id) where is_primary;
create index product_images_product_order_idx on public.product_images(product_id,display_order);
alter table public.categories enable row level security;
alter table public.brands enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
revoke all on public.categories,public.brands,public.products,public.product_images from anon,authenticated;
grant select on public.categories,public.brands,public.products,public.product_images to anon,authenticated;
create policy "Public read categories" on public.categories for select to anon,authenticated using(true);
create policy "Public read brands" on public.brands for select to anon,authenticated using(true);
create policy "Public read active products" on public.products for select to anon,authenticated using(is_active);
create policy "Public read active product images" on public.product_images for select to anon,authenticated using(exists(select 1 from public.products p where p.id=product_id and p.is_active));
